#!/usr/bin/env python3
"""
scripts/enrich_csv.py

Fixes the metadata.csv generated by convert_and_rename.py:

1. Replaces all "Unknown" values with sensible defaults per category folder.
2. Fixes the folder mismatch: 06_portfolio_samples → 06_designer_portfolio.
3. Reassigns sequential unique IDs across all rows (img_0001 ... img_1262).
4. Writes the fixed CSV back to seed_data/metadata.csv (backs up the original first).

Run once:
  python scripts/enrich_csv.py

Then optionally open the CSV and hand-tune individual rows before seeding.
"""

import csv
import shutil
import sys
from pathlib import Path
from datetime import datetime
import random

ROOT = Path(__file__).resolve().parent.parent
CSV_PATH = ROOT / "seed_data" / "metadata.csv"

# ── Enrichment rules keyed by the folder name in the filepath ─────────────
# Each entry is a list of possible values — the script rotates through them
# to create variety across rows from the same folder.

ENRICHMENT: dict[str, dict] = {
    "01_traditional_clothing": {
        "category":    "Traditional Clothing",
        "traditional": "True",
        "regions":     ["Northwest", "West", "Littoral", "Southwest", "Centre"],
        "occasions":   ["Wedding", "Traditional Ceremony", "Funeral", "Graduation", "Cultural Festival"],
        "price_range": ["mid-range", "premium", "mid-range", "mid-range", "premium"],
    },
    "02_modern_clothing": {
        "category":    "Modern Clothing",
        "traditional": "False",
        "regions":     ["Centre", "Littoral", "West", "Adamawa", "South"],
        "occasions":   ["Office", "Casual", "Date Night", "Church", "Graduation"],
        "price_range": ["budget", "mid-range", "mid-range", "budget", "premium"],
    },
    "03_traditional_hairstyles": {
        "category":    "Traditional Hairstyle",
        "traditional": "True",
        "regions":     ["Northwest", "West", "Littoral", "Centre", "South"],
        "occasions":   ["Wedding", "Traditional Ceremony", "Cultural Festival", "Graduation", "Funeral"],
        "price_range": ["budget", "budget", "mid-range", "budget", "mid-range"],
    },
    "04_modern_hairstyles": {
        "category":    "Modern Hairstyle",
        "traditional": "False",
        "regions":     ["Centre", "Littoral", "West", "South", "East"],
        "occasions":   ["Casual", "Office", "Date Night", "Church", "Graduation"],
        "price_range": ["budget", "budget", "budget", "mid-range", "budget"],
    },
    "05_accessories": {
        "category":    "Accessories",
        "traditional": "True",
        "regions":     ["West", "Northwest", "Littoral", "Centre", "South"],
        "occasions":   ["Wedding", "Traditional Ceremony", "Casual", "Cultural Festival", "Graduation"],
        "price_range": ["budget", "budget", "budget", "mid-range", "budget"],
    },
    # Handles BOTH 06_designer_portfolio and 06_portfolio_samples
    "06_designer_portfolio": {
        "category":    "Designer Portfolio",
        "traditional": "False",
        "regions":     ["Littoral", "Centre", "West", "Northwest", "South"],
        "occasions":   ["Wedding", "Office", "Casual", "Graduation", "Cultural Festival"],
        "price_range": ["premium", "premium", "mid-range", "premium", "mid-range"],
    },
    "06_portfolio_samples": {
        "category":    "Designer Portfolio",
        "traditional": "False",
        "regions":     ["Littoral", "Centre", "West", "Northwest", "South"],
        "occasions":   ["Wedding", "Office", "Casual", "Graduation", "Cultural Festival"],
        "price_range": ["premium", "premium", "mid-range", "premium", "mid-range"],
    },
}


def get_folder_from_filepath(filepath: str) -> str:
    """Extract the category folder name from a filepath like seed_data/images/01_.../image.jpg"""
    parts = filepath.replace("\\", "/").split("/")
    # Expected: seed_data / images / <folder> / filename
    if len(parts) >= 3:
        return parts[-2]
    return ""


def fix_portfolio_path(filepath: str) -> str:
    """Remap 06_portfolio_samples → 06_designer_portfolio in filepaths."""
    return filepath.replace("06_portfolio_samples", "06_designer_portfolio")


def enrich_row(row: dict, index: int, folder_counters: dict) -> dict:
    """Apply enrichment rules to a single CSV row."""
    folder = get_folder_from_filepath(row["filepath"])

    # Fix the mismatched portfolio folder name in the path
    row["filepath"] = fix_portfolio_path(row["filepath"])
    # Re-derive folder after fix
    folder = get_folder_from_filepath(row["filepath"])

    rules = ENRICHMENT.get(folder)
    if not rules:
        # Unknown folder — apply generic defaults
        return {
            **row,
            "id":          f"img_{index:04d}",
            "category":    row.get("category", "Other"),
            "traditional": row.get("traditional", "False"),
            "region":      "Cameroon",
            "occasion":    "Casual",
            "price_range": "mid-range",
        }

    # Rotate through the lists to create variety
    counter = folder_counters.get(folder, 0)
    n = len(rules["regions"])
    pos = counter % n

    folder_counters[folder] = counter + 1

    return {
        "id":          f"img_{index:04d}",
        "filepath":    row["filepath"],
        "category":    rules["category"],
        "traditional": rules["traditional"],
        "region":      rules["regions"][pos],
        "occasion":    rules["occasions"][pos],
        "price_range": rules["price_range"][pos],
    }


def main() -> None:
    if not CSV_PATH.exists():
        print(f"ERROR: metadata.csv not found at {CSV_PATH}")
        print("Run convert_and_rename.py first, then this script.")
        sys.exit(1)

    # ── Backup original ───────────────────────────────────────────────
    backup_path = CSV_PATH.with_suffix(f".backup_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv")
    shutil.copy2(CSV_PATH, backup_path)
    print(f"Backed up original CSV to: {backup_path.name}")

    # ── Read ──────────────────────────────────────────────────────────
    with open(CSV_PATH, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    print(f"Loaded {len(rows)} rows from metadata.csv")

    # ── Enrich ────────────────────────────────────────────────────────
    folder_counters: dict[str, int] = {}
    enriched = []
    unknown_before = sum(1 for r in rows if r.get("region", "") == "Unknown")

    for idx, row in enumerate(rows, start=1):
        enriched.append(enrich_row(row, idx, folder_counters))

    # ── Write ─────────────────────────────────────────────────────────
    fieldnames = ["id", "filepath", "category", "traditional", "region", "occasion", "price_range"]
    with open(CSV_PATH, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(enriched)

    # ── Report ────────────────────────────────────────────────────────
    from collections import Counter
    cat_counts = Counter(r["category"] for r in enriched)
    portfolio_fixed = sum(1 for r in enriched if "06_designer_portfolio" in r["filepath"])

    print(f"\n✅ Enrichment complete. {len(enriched)} rows written.")
    print(f"   Replaced {unknown_before} 'Unknown' region/occasion/price_range values.")
    print(f"   Portfolio path fixed: {portfolio_fixed} rows now point to 06_designer_portfolio/")
    print("\nCategory breakdown:")
    for cat, count in sorted(cat_counts.items()):
        print(f"   {cat:<30} {count} images")
    print(f"\nNext step: python scripts/seed_pinecone.py --dry-run")


if __name__ == "__main__":
    main()
