/**
 * lib/payments/mtn.ts
 *
 * MTN Mobile Money (MoMo) Collections API client.
 *
 * Sandbox docs: https://momodeveloper.mtn.com/api-documentation/collection/
 *
 * Flow:
 *   1. Request a payment (requestToPay) → provider returns 202 Accepted
 *   2. Provider processes async → sends webhook to /api/payments/callback
 *   3. We verify the webhook and update the order
 *
 * All requests go over HTTPS (enforced by the https:// base URL).
 * Credentials come from environment variables — never hardcoded.
 */

import { v4 as uuidv4 } from "uuid";

// ── Config ────────────────────────────────────────────────────────────────────

const BASE_URL =
  process.env.MTN_MOMO_ENVIRONMENT === "production"
    ? "https://proxy.momoapi.mtn.com"
    : "https://sandbox.momodeveloper.mtn.com";

const SUBSCRIPTION_KEY = process.env.MTN_MOMO_SUBSCRIPTION_KEY!;
const API_USER         = process.env.MTN_MOMO_API_USER!;
const API_KEY          = process.env.MTN_MOMO_API_KEY!;
const CURRENCY         = "XAF";
const CALLBACK_URL     = `${process.env.NEXT_PUBLIC_APP_URL}/api/payments/callback`;

// ── Types ─────────────────────────────────────────────────────────────────────

export interface MtnRequestToPayParams {
  /** Amount in XAF (integer) */
  amountXAF: number;
  /** Payer's phone number in E.164 format e.g. +237612345678 */
  payerPhone: string;
  /** Internal reference ID (our Transaction.id) */
  externalId: string;
  /** Short description shown to payer */
  payerMessage: string;
  payeeNote: string;
}

export interface MtnRequestToPayResult {
  /** UUID generated by us — used to poll status */
  referenceId: string;
  /** HTTP status from MTN: 202 = accepted, anything else = failed */
  accepted: boolean;
  error?: string;
}

export interface MtnPaymentStatus {
  status: "SUCCESSFUL" | "FAILED" | "PENDING";
  financialTransactionId?: string;
  reason?: string;
}

// ── Auth header ───────────────────────────────────────────────────────────────

function getAuthHeader(): string {
  const credentials = Buffer.from(`${API_USER}:${API_KEY}`).toString("base64");
  return `Basic ${credentials}`;
}

// ── Request to Pay ────────────────────────────────────────────────────────────

export async function mtnRequestToPay(
  params: MtnRequestToPayParams
): Promise<MtnRequestToPayResult> {
  const referenceId = uuidv4();

  const body = {
    amount:          String(params.amountXAF),
    currency:        CURRENCY,
    externalId:      params.externalId,
    payer: {
      partyIdType: "MSISDN",
      partyId:     params.payerPhone.replace(/^\+/, ""), // MTN expects no leading +
    },
    payerMessage: params.payerMessage,
    payeeNote:    params.payeeNote,
  };

  try {
    const response = await fetch(
      `${BASE_URL}/collection/v1_0/requesttopay`,
      {
        method: "POST",
        headers: {
          "Authorization":          getAuthHeader(),
          "X-Reference-Id":         referenceId,
          "X-Target-Environment":   process.env.MTN_MOMO_ENVIRONMENT ?? "sandbox",
          "Ocp-Apim-Subscription-Key": SUBSCRIPTION_KEY,
          "Content-Type":           "application/json",
          "X-Callback-Url":         CALLBACK_URL,
        },
        body: JSON.stringify(body),
        // 30-second timeout per spec
        signal: AbortSignal.timeout(30_000),
      }
    );

    if (response.status === 202) {
      return { referenceId, accepted: true };
    }

    const text = await response.text().catch(() => "");
    return { referenceId, accepted: false, error: `MTN returned ${response.status}: ${text}` };
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    return { referenceId, accepted: false, error: msg };
  }
}

// ── Poll payment status ───────────────────────────────────────────────────────

export async function mtnGetPaymentStatus(
  referenceId: string
): Promise<MtnPaymentStatus> {
  try {
    const response = await fetch(
      `${BASE_URL}/collection/v1_0/requesttopay/${referenceId}`,
      {
        headers: {
          "Authorization":             getAuthHeader(),
          "X-Target-Environment":      process.env.MTN_MOMO_ENVIRONMENT ?? "sandbox",
          "Ocp-Apim-Subscription-Key": SUBSCRIPTION_KEY,
        },
        signal: AbortSignal.timeout(10_000),
      }
    );

    if (!response.ok) {
      return { status: "FAILED", reason: `MTN status check returned ${response.status}` };
    }

    const data = await response.json() as {
      status: string;
      financialTransactionId?: string;
      reason?: { code?: string; message?: string };
    };

    return {
      status:                 data.status as MtnPaymentStatus["status"],
      financialTransactionId: data.financialTransactionId,
      reason:                 data.reason?.message,
    };
  } catch (err) {
    return { status: "FAILED", reason: err instanceof Error ? err.message : String(err) };
  }
}
